# Generated by Django 4.2.8 on 2023-12-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('imagem', models.ImageField(upload_to='Projetos/')),
                ('descricao', models.CharField(max_length=155, verbose_name='Descrição')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.instituicao')),
                ('oficina', models.ManyToManyField(to='aplic.oficina')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
