# Generated by Django 4.2.8 on 2023-12-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_professor_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('data_publicacao', models.DateField(verbose_name='Data da Publicação')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('descricao', models.CharField(max_length=155, verbose_name='Descrição')),
                ('texto_noticia', models.TextField(verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='noticia',
            field=models.ManyToManyField(to='aplic.noticia'),
        ),
    ]
