# Generated by Django 4.2.8 on 2023-12-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(default=1, upload_to='Noticias/'),
            preserve_default=False,
        ),
    ]
