# Generated by Django 4.2.8 on 2023-12-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_alter_oficina_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(upload_to='projetos/'),
        ),
    ]
