# Generated by Django 4.2.8 on 2023-12-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='dia_aulas',
            field=models.CharField(choices=[('Segunda-Feira', 'Segunda-Feira'), ('Terça-Feira', 'Terça-Feira'), ('Quarta-Feira', 'Quarta-Feira'), ('Quinta-feira', 'Quinta-Feira'), ('Sexta-Feira', 'Sexta-Feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=13, verbose_name='Dia das Aulas'),
        ),
    ]
