# Generated by Django 4.2.8 on 2024-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0012_oficina_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='descricao',
        ),
        migrations.AddField(
            model_name='noticia',
            name='area',
            field=models.TextField(default=1, help_text='Insira a área da Notícia, como Artes cênicas, canto', verbose_name='Área da Oficina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='resumo',
            field=models.CharField(default=1, max_length=155, verbose_name='Resumo'),
            preserve_default=False,
        ),
    ]
