# Generated by Django 4.2.8 on 2024-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0013_remove_noticia_descricao_noticia_area_noticia_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='cargo',
            field=models.CharField(default=1, max_length=255, verbose_name='Cargo'),
            preserve_default=False,
        ),
    ]
