# Generated by Django 4.2.8 on 2024-02-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0014_professor_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='imagem',
            field=models.ImageField(default=1, upload_to='Professor/'),
            preserve_default=False,
        ),
    ]
